CREATE TABLE cliente (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         nome VARCHAR(100) NOT NULL,
                         email VARCHAR(100) NOT NULL,
                         telefone VARCHAR(20)
);
